//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        public virtual DbSet<act_zirsarfasls> act_zirsarfasls { get; set; }
        public virtual DbSet<overal_setting> overal_setting { get; set; }
        public virtual DbSet<sarfasl> sarfasls { get; set; }
        public virtual DbSet<zirsarfasl> zirsarfasls { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<SubSystem> SubSystems { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<GroupSarfasl> GroupSarfasls { get; set; }
        public virtual DbSet<sys_users> sys_users { get; set; }
        public virtual DbSet<UserFavorite> UserFavorites { get; set; }
        public virtual DbSet<sal_mali> sal_mali { get; set; }
    
        public virtual ObjectResult<USP_GetDataForSarfasl_Result> USP_GetDataForSarfasl(string fromDate, string toDate, string listGroupSarfasl, string listSarfasl, string listZirSarfasl)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var listGroupSarfaslParameter = listGroupSarfasl != null ?
                new ObjectParameter("listGroupSarfasl", listGroupSarfasl) :
                new ObjectParameter("listGroupSarfasl", typeof(string));
    
            var listSarfaslParameter = listSarfasl != null ?
                new ObjectParameter("listSarfasl", listSarfasl) :
                new ObjectParameter("listSarfasl", typeof(string));
    
            var listZirSarfaslParameter = listZirSarfasl != null ?
                new ObjectParameter("listZirSarfasl", listZirSarfasl) :
                new ObjectParameter("listZirSarfasl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetDataForSarfasl_Result>("USP_GetDataForSarfasl", fromDateParameter, toDateParameter, listGroupSarfaslParameter, listSarfaslParameter, listZirSarfaslParameter);
        }
    
        public virtual ObjectResult<USP_GetDataStimulSoft_Sarfasl_ZirSarfasl_Result> USP_GetDataStimulSoft_Sarfasl_ZirSarfasl(string fromdate, string todate, Nullable<int> sarfaslID, string listZirSarfasl)
        {
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(string));
    
            var todateParameter = todate != null ?
                new ObjectParameter("Todate", todate) :
                new ObjectParameter("Todate", typeof(string));
    
            var sarfaslIDParameter = sarfaslID.HasValue ?
                new ObjectParameter("SarfaslID", sarfaslID) :
                new ObjectParameter("SarfaslID", typeof(int));
    
            var listZirSarfaslParameter = listZirSarfasl != null ?
                new ObjectParameter("ListZirSarfasl", listZirSarfasl) :
                new ObjectParameter("ListZirSarfasl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetDataStimulSoft_Sarfasl_ZirSarfasl_Result>("USP_GetDataStimulSoft_Sarfasl_ZirSarfasl", fromdateParameter, todateParameter, sarfaslIDParameter, listZirSarfaslParameter);
        }
    }
}
