//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSarfasl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupSarfasl()
        {
            this.sarfasls = new HashSet<sarfasl>();
        }
    
        public int GroupSarfaslID { get; set; }
        public string GroupSarfaslName { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sarfasl> sarfasls { get; set; }
    }
}
