//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sarfasl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sarfasl()
        {
            this.zirsarfasls = new HashSet<zirsarfasl>();
        }
    
        public int rdf { get; set; }
        public string name { get; set; }
        public string has_dar { get; set; }
        public string who_def { get; set; }
        public string start_date { get; set; }
        public Nullable<bool> Active { get; set; }
        public int GroupSarfaslID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zirsarfasl> zirsarfasls { get; set; }
        public virtual GroupSarfasl GroupSarfasl { get; set; }
    }
}
