//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atiran.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zirsarfasl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zirsarfasl()
        {
            this.act_zirsarfasls = new HashSet<act_zirsarfasls>();
        }
    
        public int rdf { get; set; }
        public Nullable<int> radif { get; set; }
        public int rdf_sarfasl { get; set; }
        public string name { get; set; }
        public string has_dar { get; set; }
        public decimal man { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<act_zirsarfasls> act_zirsarfasls { get; set; }
        public virtual sarfasl sarfasl { get; set; }
    }
}
